#!/bin/bash

if [ ! -f Makefile ]; then
        echo "Generate a Makefile using qmake first."
        exit 1
fi
make
sudo make install
sudo mkdir -p /usr/include/phitron/
sudo cp *.h /usr/include/phitron/
